"""Initial migration

Revision ID: a30d74691a61
Revises: 
Create Date: 2024-12-06 15:09:33.896386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30d74691a61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('hobbies')
    op.drop_table('photos')
    op.drop_table('likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('liked_user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.UniqueConstraint('id', 'user_id', 'liked_user_id', name='likes_key')
    )
    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('id', 'user_id', name='photos_unique')
    )
    op.create_table('hobbies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.UniqueConstraint('id', 'user_id', 'category_id', name='hobbies_key')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('id', name='categories_unique')
    )
    # ### end Alembic commands ###
